[platformio]
src_dir = starcore-v2

[env:starcore-v2]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
lib_extra_dirs =
    starcore-v2/libraries
    shared-libraries
